<?php
// fecha actual para el footer
$fecha = new DateTime();

?>

</div>
</main>
<footer class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top">
    <div class="align-items-center">
        <span class="text-muted"><?= $fecha->format('Y') ?> Manuel Montoya - TUDAI, UNICEN</span>
    </div>
</footer>
<script src="http://localhost:35729/livereload.js"></script>

</body>

</html>