    <!DOCTYPE html>
<html lang="en">

<head>
    <base href="<?php echo BASE_URL ?>" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WEB 2 - 2025</title>
    <link rel="stylesheet" href="./css/styles.css?v=<?= time(); ?>">
</head>

<?php
function showExercisesList($id)
{
        switch ($id) {


            // TRABAJO PRACTICO 1 -> INTRO PHP
            case '1':
                echo "
                <div id='nav-links'>";
                for ($i = 1; $i < 9; $i++) {
                    echo "
                    <a class='nav-link' href='Unidad/$id/ejercicio$i'>Ejercicio $i</a>";
                }
                echo "
                </div>";
                break;


            // TRABAJO PRACTICO 2 -> RUTEO    
            case '2':
                echo "
                <div id='nav-links'>";
                for ($i = 1; $i <= 7; $i++) {
                    echo "
                    <a class='nav-link' href='Unidad/$id/ejercicio$i'>Ejercicio $i</a>";
                }
                echo "
                </div>";
                break;

            default:
                die();
        }
    }
function showHeader($ejercicio = null) {
echo '

<body>
    <header class="container-encabezado">
        <section id="left-menu">
            <h1 id="nav-title">WEB2 - 2025 | Ejercicios</h1>
            <div id="tittle-links-container">
                <a href="Home" class="title-links" data-target="tp1">Home</a>
                <a href="About" class="title-links" data-target="tp1">Learn</a>
                <a href="../PhotoAlbum" class="title-links">PhotoAlbum</a>
                <a href="../Figuras" class="title-links">Figuras</a>
            </div>
        </section>

        <nav class="nav-menu">
            <ul id="nav-list">
                <li><a href="Unidad/1" class="nav-link big">TP1</a></li>
                <li><a href="Unidad/2" class="nav-link big">TP2</a></li>
                <li><a href="Unidad/3" class="nav-link big">TP3</a></li>
                <li><a href="Unidad/4" class="nav-link big">TP4</a></li>
            </ul>
    ';
    if ($ejercicio === '1' || $ejercicio === '2') {
        showExercisesList($ejercicio);
    }
    echo '
            </nav>
        </header>

        <main class="container-principal">
            <div class="container-ejercicios">';
    
}
