<!DOCTYPE html>
<html lang="en">

<head>
    <base href="<?php echo BASE_URL?>"/>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../docs/css/styles.css?v=<?= time(); ?>">
    <title>PhotoAlbum [TP2-ex6]</title>
</head>

<body>
    <header class="container-encabezado">
        <section id="left-menu">
            <h1 id="nav-title">WEB2 - 2025 | Ejercicios</h1>
            <div id='tittle-links-container'>
                <a href="../docs/Home" class="title-links" data-target="tp1">Home</a>
                <a href="../docs/About" class="title-links" data-target="tp1">Learn</a>
                <a href="../PhotoAlbum" class="title-links">PhotoAlbum</a>
                <a href="../Figuras" class="title-links">Figuras</a>

            </div>
        </section>

        <nav class="nav-menu">
            <ul id="nav-list">
                <li><a href="../docs/Unidad/1" class="nav-link big">TP1</a></li>
                <li><a href="../docs/Unidad/2" class="nav-link big">TP2</a></li>
                <li><a href="../docs/Unidad/3" class="nav-link big">TP3</a></li>
                <li><a href="../docs/Unidad/4" class="nav-link big">TP4</a></li>
            </ul>

        </nav>
    </header>
    <main class="container-principal">
        <div class="container-ejercicios">