<section class="card">
    <h1>Figuras</h1>
    <a class="card-links" href="lista">Ver todas las figuras geométricas</a>
    <a class="card-links" href="../site/Unidad/2/ejercicio7">Volver atrás</a>
    <form class="forms-tp" action="Filtro" method="GET">
        <label for="area">Buscar figuras con área menor a: </label>
        <input id="area" type="number" name="area" placeholder="Introduzca área...">
        <button type="submit">Buscar</button>
    </form>
</section>