
        <section class="other">
            <h1>Hola mundo!</h1>
            <h3> Bienvenido a la resolucion de ejercicios de los trabajos prácticos de Web 2!</h3>
            <h1>Todavia estamos en proceso de desarrollo!</h1>
            <h3> Pronto, muchos mas ejercicios resueltos!</h3>
        </section>

<?php
// $str = '

// ';
// echo $str;

// function welcome()
// {
//     echo '

//      <main class="container-principal">
//      <div class="container-ejercicios">
//      <section class="card">
//      <h1>Hola mundo!</h1>
//      <h3> Bienvenido a la resolucion de ejercicios de los trabajos prácticos de Web 2!</h3>
//      <h1>Todavia estamos en proceso de desarrollo!</h1>
//      <h3> Pronto, muchos mas ejercicios resueltos!</h3>
//      </section>
//      </div>
//      </main>

//  ';
// }
?>